# Generated by Django 4.1.2 on 2022-10-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('salario', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('email', models.IntegerField(max_length=200)),
            ],
            options={
                'db_table': 'operador',
            },
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('salario', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'piloto',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_atual', models.IntegerField(primary_key=True, serialize=False)),
                ('proximo_status', models.IntegerField()),
                ('horario', models.DateTimeField()),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('codigo_de_voo', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('aeroporto_destino', models.CharField(max_length=200)),
                ('aeroporto_partida', models.CharField(max_length=200)),
                ('partida_prevista', models.DateTimeField()),
                ('partida_real', models.DateTimeField(null=True)),
                ('chegada_prevista', models.DateTimeField()),
                ('chegada_real', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'voo',
            },
        ),
        migrations.CreateModel(
            name='Companhia_Aerea',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('id_companhia_aerea', models.IntegerField(primary_key=True, serialize=False)),
                ('funcionarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.funcionario')),
                ('pilotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.piloto')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.voo')),
            ],
            options={
                'db_table': 'companhia_aerea',
            },
        ),
    ]
