# Generated by Django 4.1.2 on 2022-10-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'livros',
            },
        ),
    ]
