# Generated by Django 4.1.2 on 2022-10-06 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_funcionario_operador_piloto_status_voo_delete_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='companhia_aerea',
        ),
        migrations.RemoveField(
            model_name='piloto',
            name='companhia_aerea',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='companhia_aerea',
        ),
        migrations.CreateModel(
            name='Companhia_Area',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('id_companhia_aerea', models.IntegerField(primary_key=True, serialize=False)),
                ('funcionarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.funcionario')),
                ('pilotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.piloto')),
            ],
            options={
                'db_table': 'companhia_aerea',
            },
        ),
    ]
