# Generated by Django 4.1.2 on 2022-10-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_funcionario_companhia_aerea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companhia',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('id_companhia_aerea', models.IntegerField(primary_key=True, serialize=False)),
                ('funcionarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.funcionario')),
                ('pilotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.piloto')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.voo')),
            ],
            options={
                'db_table': 'companhia',
            },
        ),
        migrations.DeleteModel(
            name='Companhia_Area',
        ),
    ]
